import { describe, expect, it, beforeAll } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { createRender } from '@/pipeline/render';
import type { RenderJob } from '@/types';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const FIXTURE_DIR = path.join(REPO_ROOT, 'tests', 'fixtures', 'render');
const MASK_DIR = path.join(REPO_ROOT, 'public');
const OUT_DIR = path.join(FIXTURE_DIR, '.out');

// Skip if ffmpeg isn't available in this environment.
const haveFfmpeg = spawnSync('ffmpeg', ['-version'], { stdio: 'ignore' }).status === 0;
const maybe = haveFfmpeg ? describe : describe.skip;

async function makeShotPng(pathOut: string, height: number): Promise<void> {
  // Tall vertical gradient so the pan is visible at a glance.
  const width = 1920;
  const buf = Buffer.alloc(width * height * 3);
  for (let y = 0; y < height; y++) {
    const r = Math.floor(255 * (y / height));
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 3;
      buf[i] = r;
      buf[i + 1] = 50;
      buf[i + 2] = 200;
    }
  }
  await sharp(buf, { raw: { width, height, channels: 3 } }).png().toFile(pathOut);
}

async function makeCirclePng(pathOut: string, size = 400): Promise<void> {
  await sharp({
    create: { width: size, height: size, channels: 3, background: { r: 200, g: 50, b: 50 } },
  })
    .png()
    .toFile(pathOut);
}

// Generate a short test video at the given dimensions, optionally with audio.
// Uses ffmpeg's lavfi sources so no external assets needed.
function makeCircleVideo(pathOut: string, durationSec: number, withAudio: boolean, width = 640, height = 360): void {
  const args = ['-y', '-f', 'lavfi', '-i', `testsrc=size=${width}x${height}:rate=30:duration=${durationSec}`];
  if (withAudio) {
    args.push('-f', 'lavfi', '-i', `sine=frequency=440:duration=${durationSec}`, '-c:a', 'aac', '-shortest');
  } else {
    args.push('-an');
  }
  args.push('-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-t', String(durationSec), pathOut);
  const r = spawnSync('ffmpeg', args, { stdio: 'pipe', encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`failed to generate fixture video: ${r.stderr}`);
}

function ffprobeJson(file: string): { streams: Array<Record<string, unknown>>; format: Record<string, unknown> } {
  const r = spawnSync('ffprobe', ['-v', 'error', '-print_format', 'json', '-show_format', '-show_streams', file], { encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`ffprobe failed: ${r.stderr}`);
  return JSON.parse(r.stdout) as { streams: Array<Record<string, unknown>>; format: Record<string, unknown> };
}

beforeAll(async () => {
  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(FIXTURE_DIR, { recursive: true });
});

maybe('render integration (real ffmpeg)', () => {
  it('produces a valid silent MP4 from PNG screenshot + image circle', async () => {
    const shotPath = path.join(FIXTURE_DIR, 'shot.png');
    const circlePath = path.join(FIXTURE_DIR, 'circle.png');
    const outPath = path.join(OUT_DIR, 'silent.mp4');

    await makeShotPng(shotPath, 4000);
    await makeCirclePng(circlePath);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 4000,
      circleSourcePath: circlePath,
      circleHasAudio: false,
      outputPath: outPath,
      config: {
        durationSec: 2,            // keep tests fast
        resolution: '720p',
        circlePosition: 'bottom-right',
        circleSize: 'S',
        circleMargin: 20,
        filenameTemplate: '',
      },
    };

    const render = createRender({ maskDir: MASK_DIR });
    const result = await render(job);

    expect(result.outputPath).toBe(outPath);
    expect(result.durationMs).toBeGreaterThan(0);

    const st = await stat(outPath);
    expect(st.size).toBeGreaterThan(1000);

    const probe = ffprobeJson(outPath);
    const video = probe.streams.find((s) => s.codec_type === 'video');
    expect(video).toBeDefined();
    expect(video!.codec_name).toBe('h264');
    expect(video!.width).toBe(1280);
    expect(video!.height).toBe(720);
    // No audio stream when input is silent.
    expect(probe.streams.find((s) => s.codec_type === 'audio')).toBeUndefined();
  }, 60_000);

  it('renders with mp3 audio when audioPath is set, output has aac stream', async () => {
    const shotPath = path.join(FIXTURE_DIR, 'shot.png');
    const circlePath = path.join(FIXTURE_DIR, 'circle.png');
    const audioPath = path.join(FIXTURE_DIR, 'tone.mp3');
    const outPath = path.join(OUT_DIR, 'with-mp3.mp4');

    await makeShotPng(shotPath, 4000);
    await makeCirclePng(circlePath);

    // 2s sine-tone mp3 generated by ffmpeg itself.
    const gen = spawnSync('ffmpeg', ['-y', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2', '-c:a', 'libmp3lame', audioPath], { stdio: 'ignore' });
    expect(gen.status).toBe(0);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 4000,
      circleSourcePath: circlePath,
      circleHasAudio: false,
      audioPath,
      outputPath: outPath,
      config: {
        durationSec: 2,
        resolution: '720p',
        circlePosition: 'top-left',
        circleSize: 'S',
        circleMargin: 20,
        filenameTemplate: '',
      },
    };

    const render = createRender({ maskDir: MASK_DIR });
    await render(job);

    const probe = ffprobeJson(outPath);
    const audio = probe.streams.find((s) => s.codec_type === 'audio');
    expect(audio).toBeDefined();
    expect(audio!.codec_name).toBe('aac');
  }, 60_000);

  it('renders a 1280×800 capture to 1080p — pre-scale + ih-based pan must work', async () => {
    // This is the exact case the UI used to hit before the filter-graph fix:
    // a viewport-sized capture (1280-wide) rendered at 1080p output (1920×1080).
    // Without pre-scaling, ffmpeg errored out with "crop input width less than
    // crop width". With the fix, we expect a clean 1920×1080 H.264 MP4.
    const shotPath = path.join(FIXTURE_DIR, 'shot-1280x800.png');
    const circlePath = path.join(FIXTURE_DIR, 'circle.png');
    const outPath = path.join(OUT_DIR, 'narrow-to-1080p.mp4');

    await makeShotPng(shotPath, 800);   // 1280×800 — same width as the makeShotPng default
    await makeCirclePng(circlePath);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 800,
      circleSourcePath: circlePath,
      circleHasAudio: false,
      outputPath: outPath,
      config: {
        durationSec: 2,
        resolution: '1080p',
        circlePosition: 'bottom-right',
        circleSize: 'M',
        circleMargin: 40,
        filenameTemplate: '',
      },
    };

    const render = createRender({ maskDir: MASK_DIR });
    const result = await render(job);
    expect(result.outputPath).toBe(outPath);

    const probe = ffprobeJson(outPath);
    const video = probe.streams.find((s) => s.codec_type === 'video');
    expect(video).toBeDefined();
    expect(video!.codec_name).toBe('h264');
    expect(video!.width).toBe(1920);
    expect(video!.height).toBe(1080);
  }, 60_000);

  it('renders a 1280×800 capture to 720p — regression check that 720p still works', async () => {
    // Same input dims as above but the original happy path — guard against
    // the fix accidentally regressing the resolution that previously worked.
    const shotPath = path.join(FIXTURE_DIR, 'shot-1280x800.png');
    const circlePath = path.join(FIXTURE_DIR, 'circle.png');
    const outPath = path.join(OUT_DIR, 'narrow-to-720p.mp4');

    await makeShotPng(shotPath, 800);
    await makeCirclePng(circlePath);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 800,
      circleSourcePath: circlePath,
      circleHasAudio: false,
      outputPath: outPath,
      config: {
        durationSec: 2,
        resolution: '720p',
        circlePosition: 'top-left',
        circleSize: 'S',
        circleMargin: 20,
        filenameTemplate: '',
      },
    };

    const render = createRender({ maskDir: MASK_DIR });
    await render(job);
    const probe = ffprobeJson(outPath);
    const video = probe.streams.find((s) => s.codec_type === 'video');
    expect(video!.width).toBe(1280);
    expect(video!.height).toBe(720);
  }, 60_000);

  // ─── Circle source: video instead of image ──────────────────────────────
  // The capture is the same; what changes is [1:v]/[1:a]. The render must
  // crop the rectangular video into a circle (alphamerge with the mask) and,
  // when circleHasAudio is true, route that audio through the filter graph.

  it('renders with a VIDEO circle source (silent video, no MP3) — output has no audio', async () => {
    const shotPath = path.join(FIXTURE_DIR, 'shot-vc.png');
    const videoPath = path.join(FIXTURE_DIR, 'circle-silent.mp4');
    const outPath = path.join(OUT_DIR, 'video-circle-silent.mp4');

    await makeShotPng(shotPath, 4000);
    makeCircleVideo(videoPath, 2, false, 640, 480);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 4000,
      circleSourcePath: videoPath,
      circleHasAudio: false,
      outputPath: outPath,
      config: {
        durationSec: 2,
        resolution: '720p',
        circlePosition: 'bottom-right',
        circleSize: 'M',
        circleMargin: 30,
        filenameTemplate: '',
      },
    };
    await createRender({ maskDir: MASK_DIR })(job);

    const probe = ffprobeJson(outPath);
    expect(probe.streams.find((s) => s.codec_type === 'video')!.codec_name).toBe('h264');
    expect(probe.streams.find((s) => s.codec_type === 'audio')).toBeUndefined();
  }, 60_000);

  it('renders with a VIDEO circle source carrying its own audio — output has aac', async () => {
    const shotPath = path.join(FIXTURE_DIR, 'shot-vc.png');
    const videoPath = path.join(FIXTURE_DIR, 'circle-with-audio.mp4');
    const outPath = path.join(OUT_DIR, 'video-circle-audio.mp4');

    await makeShotPng(shotPath, 4000);
    makeCircleVideo(videoPath, 2, true, 640, 480);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 4000,
      circleSourcePath: videoPath,
      circleHasAudio: true,
      outputPath: outPath,
      config: {
        durationSec: 2,
        resolution: '1080p',     // also exercises the 1080p fix on top of video circle
        circlePosition: 'top-right',
        circleSize: 'L',
        circleMargin: 50,
        filenameTemplate: '',
      },
    };
    await createRender({ maskDir: MASK_DIR })(job);

    const probe = ffprobeJson(outPath);
    const v = probe.streams.find((s) => s.codec_type === 'video')!;
    expect(v.codec_name).toBe('h264');
    expect(v.width).toBe(1920);
    expect(v.height).toBe(1080);
    const a = probe.streams.find((s) => s.codec_type === 'audio')!;
    expect(a.codec_name).toBe('aac');
  }, 60_000);

  it('VIDEO circle audio + MP3 narration → amix path, output has aac', async () => {
    const shotPath = path.join(FIXTURE_DIR, 'shot-vc.png');
    const videoPath = path.join(FIXTURE_DIR, 'circle-amix.mp4');
    const audioPath = path.join(FIXTURE_DIR, 'narration-amix.mp3');
    const outPath = path.join(OUT_DIR, 'video-circle-amix.mp4');

    await makeShotPng(shotPath, 4000);
    makeCircleVideo(videoPath, 2, true, 640, 480);
    // Generate a 2s mp3 narration via lavfi.
    const gen = spawnSync('ffmpeg', ['-y', '-f', 'lavfi', '-i', 'sine=frequency=220:duration=2', '-c:a', 'libmp3lame', audioPath], { stdio: 'ignore' });
    expect(gen.status).toBe(0);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 4000,
      circleSourcePath: videoPath,
      circleHasAudio: true,
      audioPath,
      outputPath: outPath,
      config: {
        durationSec: 2,
        resolution: '720p',
        circlePosition: 'bottom-left',
        circleSize: 'M',
        circleMargin: 30,
        filenameTemplate: '',
      },
    };
    await createRender({ maskDir: MASK_DIR })(job);

    const probe = ffprobeJson(outPath);
    expect(probe.streams.find((s) => s.codec_type === 'audio')!.codec_name).toBe('aac');
  }, 60_000);

  it('short circle video + longer output — overlay holds last frame, output reaches full duration', async () => {
    // 1-second circle video, 3-second output. FFmpeg overlay's default
    // eof_action=repeat keeps the last frame on screen for the gap.
    const shotPath = path.join(FIXTURE_DIR, 'shot-vc.png');
    const videoPath = path.join(FIXTURE_DIR, 'circle-1s.mp4');
    const outPath = path.join(OUT_DIR, 'video-circle-shorter.mp4');

    await makeShotPng(shotPath, 4000);
    makeCircleVideo(videoPath, 1, false, 640, 480);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 4000,
      circleSourcePath: videoPath,
      circleHasAudio: false,
      outputPath: outPath,
      config: {
        durationSec: 3,
        resolution: '720p',
        circlePosition: 'bottom-right',
        circleSize: 'S',
        circleMargin: 20,
        filenameTemplate: '',
      },
    };
    await createRender({ maskDir: MASK_DIR })(job);

    const probe = ffprobeJson(outPath);
    const dur = Number.parseFloat(String(probe.format['duration']));
    expect(dur).toBeGreaterThanOrEqual(2.9); // ≈ 3.0 modulo container fudge
  }, 60_000);

  it('rejects with RenderError when ffmpeg exits non-zero (missing input)', async () => {
    const job: RenderJob = {
      screenshotPath: '/nonexistent/shot.png',
      screenshotHeight: 4000,
      circleSourcePath: '/nonexistent/circle.png',
      circleHasAudio: false,
      outputPath: path.join(OUT_DIR, 'should-not-exist.mp4'),
      config: {
        durationSec: 1,
        resolution: '720p',
        circlePosition: 'bottom-right',
        circleSize: 'S',
        circleMargin: 20,
        filenameTemplate: '',
      },
    };
    const render = createRender({ maskDir: MASK_DIR });
    await expect(render(job)).rejects.toMatchObject({
      name: 'RenderError',
      reason: 'ffmpeg-error',
    });
  }, 30_000);
});

// Marker so vitest considers this file even when the maybe block is skipped.
describe('render module', () => {
  it('exports render and createRender', async () => {
    const mod = await import('@/pipeline/render');
    expect(typeof mod.render).toBe('function');
    expect(typeof mod.createRender).toBe('function');
  });
});

// Quiet the unused-import warning in environments without ffmpeg.
void writeFile;
