import { describe, expect, it, beforeAll } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
import { createRender } from '@/pipeline/render';
import type { RenderJob } from '@/types';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const FIXTURE_DIR = path.join(REPO_ROOT, 'tests', 'fixtures', 'render');
const MASK_DIR = path.join(REPO_ROOT, 'public');
const OUT_DIR = path.join(FIXTURE_DIR, '.out');

// Skip if ffmpeg isn't available in this environment.
const haveFfmpeg = spawnSync('ffmpeg', ['-version'], { stdio: 'ignore' }).status === 0;
const maybe = haveFfmpeg ? describe : describe.skip;

async function makeShotPng(pathOut: string, height: number): Promise<void> {
  // Tall vertical gradient so the pan is visible at a glance.
  const width = 1920;
  const buf = Buffer.alloc(width * height * 3);
  for (let y = 0; y < height; y++) {
    const r = Math.floor(255 * (y / height));
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 3;
      buf[i] = r;
      buf[i + 1] = 50;
      buf[i + 2] = 200;
    }
  }
  await sharp(buf, { raw: { width, height, channels: 3 } }).png().toFile(pathOut);
}

async function makeCirclePng(pathOut: string, size = 400): Promise<void> {
  await sharp({
    create: { width: size, height: size, channels: 3, background: { r: 200, g: 50, b: 50 } },
  })
    .png()
    .toFile(pathOut);
}

function ffprobeJson(file: string): { streams: Array<Record<string, unknown>>; format: Record<string, unknown> } {
  const r = spawnSync('ffprobe', ['-v', 'error', '-print_format', 'json', '-show_format', '-show_streams', file], { encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`ffprobe failed: ${r.stderr}`);
  return JSON.parse(r.stdout) as { streams: Array<Record<string, unknown>>; format: Record<string, unknown> };
}

beforeAll(async () => {
  await mkdir(OUT_DIR, { recursive: true });
  await mkdir(FIXTURE_DIR, { recursive: true });
});

maybe('render integration (real ffmpeg)', () => {
  it('produces a valid silent MP4 from PNG screenshot + image circle', async () => {
    const shotPath = path.join(FIXTURE_DIR, 'shot.png');
    const circlePath = path.join(FIXTURE_DIR, 'circle.png');
    const outPath = path.join(OUT_DIR, 'silent.mp4');

    await makeShotPng(shotPath, 4000);
    await makeCirclePng(circlePath);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 4000,
      circleSourcePath: circlePath,
      circleHasAudio: false,
      outputPath: outPath,
      config: {
        durationSec: 2,            // keep tests fast
        resolution: '720p',
        circlePosition: 'bottom-right',
        circleSize: 'S',
        circleMargin: 20,
        filenameTemplate: '',
      },
    };

    const render = createRender({ maskDir: MASK_DIR });
    const result = await render(job);

    expect(result.outputPath).toBe(outPath);
    expect(result.durationMs).toBeGreaterThan(0);

    const st = await stat(outPath);
    expect(st.size).toBeGreaterThan(1000);

    const probe = ffprobeJson(outPath);
    const video = probe.streams.find((s) => s.codec_type === 'video');
    expect(video).toBeDefined();
    expect(video!.codec_name).toBe('h264');
    expect(video!.width).toBe(1280);
    expect(video!.height).toBe(720);
    // No audio stream when input is silent.
    expect(probe.streams.find((s) => s.codec_type === 'audio')).toBeUndefined();
  }, 60_000);

  it('renders with mp3 audio when audioPath is set, output has aac stream', async () => {
    const shotPath = path.join(FIXTURE_DIR, 'shot.png');
    const circlePath = path.join(FIXTURE_DIR, 'circle.png');
    const audioPath = path.join(FIXTURE_DIR, 'tone.mp3');
    const outPath = path.join(OUT_DIR, 'with-mp3.mp4');

    await makeShotPng(shotPath, 4000);
    await makeCirclePng(circlePath);

    // 2s sine-tone mp3 generated by ffmpeg itself.
    const gen = spawnSync('ffmpeg', ['-y', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2', '-c:a', 'libmp3lame', audioPath], { stdio: 'ignore' });
    expect(gen.status).toBe(0);

    const job: RenderJob = {
      screenshotPath: shotPath,
      screenshotHeight: 4000,
      circleSourcePath: circlePath,
      circleHasAudio: false,
      audioPath,
      outputPath: outPath,
      config: {
        durationSec: 2,
        resolution: '720p',
        circlePosition: 'top-left',
        circleSize: 'S',
        circleMargin: 20,
        filenameTemplate: '',
      },
    };

    const render = createRender({ maskDir: MASK_DIR });
    await render(job);

    const probe = ffprobeJson(outPath);
    const audio = probe.streams.find((s) => s.codec_type === 'audio');
    expect(audio).toBeDefined();
    expect(audio!.codec_name).toBe('aac');
  }, 60_000);

  it('rejects with RenderError when ffmpeg exits non-zero (missing input)', async () => {
    const job: RenderJob = {
      screenshotPath: '/nonexistent/shot.png',
      screenshotHeight: 4000,
      circleSourcePath: '/nonexistent/circle.png',
      circleHasAudio: false,
      outputPath: path.join(OUT_DIR, 'should-not-exist.mp4'),
      config: {
        durationSec: 1,
        resolution: '720p',
        circlePosition: 'bottom-right',
        circleSize: 'S',
        circleMargin: 20,
        filenameTemplate: '',
      },
    };
    const render = createRender({ maskDir: MASK_DIR });
    await expect(render(job)).rejects.toMatchObject({
      name: 'RenderError',
      reason: 'ffmpeg-error',
    });
  }, 30_000);
});

// Marker so vitest considers this file even when the maybe block is skipped.
describe('render module', () => {
  it('exports render and createRender', async () => {
    const mod = await import('@/pipeline/render');
    expect(typeof mod.render).toBe('function');
    expect(typeof mod.createRender).toBe('function');
  });
});

// Quiet the unused-import warning in environments without ffmpeg.
void writeFile;
